//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactsApplication.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový záznam.
        /// </summary>
        public static string Buttons_AddNew {
            get {
                return ResourceManager.GetString("Buttons.AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět na výpis.
        /// </summary>
        public static string Buttons_BackToList {
            get {
                return ResourceManager.GetString("Buttons.BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat filtry.
        /// </summary>
        public static string Buttons_ClearFilters {
            get {
                return ResourceManager.GetString("Buttons.ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string Buttons_Delete {
            get {
                return ResourceManager.GetString("Buttons.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Buttons_Detail {
            get {
                return ResourceManager.GetString("Buttons.Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string Buttons_Edit {
            get {
                return ResourceManager.GetString("Buttons.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Buttons_SaveChanges {
            get {
                return ResourceManager.GetString("Buttons.SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatný formát..
        /// </summary>
        public static string Errors_InvalidFormat {
            get {
                return ResourceManager.GetString("Errors.InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nejvýše {1} znaků..
        /// </summary>
        public static string Errors_MaxLength {
            get {
                return ResourceManager.GetString("Errors.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} je povinný údaj..
        /// </summary>
        public static string Errors_Required {
            get {
                return ResourceManager.GetString("Errors.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu smazat?.
        /// </summary>
        public static string General_ConfirmDelete {
            get {
                return ResourceManager.GetString("General.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrovat.
        /// </summary>
        public static string General_Filter {
            get {
                return ResourceManager.GetString("General.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seřadit vzestupně.
        /// </summary>
        public static string General_SortAsc {
            get {
                return ResourceManager.GetString("General.SortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seřadit sestupně.
        /// </summary>
        public static string General_SortDesc {
            get {
                return ResourceManager.GetString("General.SortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava záznamu.
        /// </summary>
        public static string Headings_EditRecord {
            get {
                return ResourceManager.GetString("Headings.EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nový záznam.
        /// </summary>
        public static string Headings_NewRecord {
            get {
                return ResourceManager.GetString("Headings.NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail záznamu.
        /// </summary>
        public static string Headings_ViewRecord {
            get {
                return ResourceManager.GetString("Headings.ViewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Město.
        /// </summary>
        public static string Labels_City {
            get {
                return ResourceManager.GetString("Labels.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Labels_Email {
            get {
                return ResourceManager.GetString("Labels.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Labels_FirstName {
            get {
                return ResourceManager.GetString("Labels.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string Labels_LastName {
            get {
                return ResourceManager.GetString("Labels.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Labels_Phone {
            get {
                return ResourceManager.GetString("Labels.Phone", resourceCulture);
            }
        }
    }
}
